load("//build/kernel/kleaf:kernel.bzl", "ddk_module")
load("//build/kernel/kleaf:kernel.bzl",
     "ddk_module", "kernel_compile_commands")

kernel_compile_commands(
    name = "smart_io_sched_compile_commands",
    deps = [":smart_io_sched"],
)

ddk_module(
    name = "smart_io_sched",
    srcs = glob([
        "**/*.c",
        "**/*.S",
    ]),
    hdrs = glob([
        "**/*.h"
    ]),
    includes = [
        ".",
        "include",
    ],
    out = "smart_io_sched.ko",
    kernel_build = "//common:kernel_aarch64",
    deps = [
        "//common:all_headers_aarch64"
    ],
)
