load("//build/kernel/kleaf:kernel.bzl", "ddk_module")

ddk_module(
    name = "smart_io_model_bench",
    srcs = [
        "smart_io_model_bench.c",
		"smart_io_model_fp32_neon.S",
		"smart_io_model_suite_fp32.S",
        "smart_io_model_suite_int8.S",
    ],
    hdrs = [
        "smart_io_model_bench_uapi.h",
		"smart_io_model_fp32_neon.h",
		"smart_io_model_fp32_params.h",
        "smart_io_model_suite_params.h",
    ],
    out = "smart_io_model_fp32_bench.ko",
    kernel_build = "//common:kernel_aarch64",
    deps = ["//common:all_headers_aarch64"],
)
