#!/usr/bin/env python3
"""Generate bit-exact kernel FP32 parameters from a joint smart_io_rl model."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

import numpy as np


ARRAYS = (
    ("weight1", "trunk.0.weight", (32, 11)),
    ("bias1", "trunk.0.bias", (32,)),
    ("weight2", "trunk.2.weight", (32, 32)),
    ("bias2", "trunk.2.bias", (32,)),
    ("joint_weight", "joint_head.weight", (12, 32)),
    ("joint_bias", "joint_head.bias", (12,)),
)


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def format_values(values: np.ndarray, indent: str) -> list[str]:
    bits = np.ascontiguousarray(values, dtype=np.float32).view(np.uint32)

    def format_row(row: np.ndarray, row_indent: str) -> list[str]:
        return [
            row_indent
            + ", ".join(f"0x{int(value):08x}" for value in row[start : start + 6])
            + ","
            for start in range(0, len(row), 6)
        ]

    if bits.ndim == 1:
        return format_row(bits, indent)
    lines: list[str] = []
    for row in bits:
        lines.append(indent + "{")
        lines.extend(format_row(row, indent + "\t"))
        lines.append(indent + "},")
    return lines


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--model-spec", type=Path, required=True)
    parser.add_argument("--weights", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    spec = json.loads(args.model_spec.read_text(encoding="utf-8"))
    architecture = spec["architecture"]
    if (
        architecture.get("type") != "joint"
        or architecture.get("state_dim") != 11
        or architecture.get("hidden_dim") != 32
        or architecture.get("action_count") != 12
        or architecture.get("action_id_definition")
        != "throttle_level_id * 3 + dispatch_policy_id"
    ):
        raise ValueError(f"unexpected architecture: {architecture}")

    with np.load(args.weights) as archive:
        weights = {}
        for c_name, artifact_name, shape in ARRAYS:
            values = archive[artifact_name].astype(np.float32, copy=False)
            if values.shape != shape or not np.isfinite(values).all():
                raise ValueError(f"invalid {artifact_name}: {values.shape}")
            weights[c_name] = values

    preprocessing = spec["preprocessing"]
    mean = np.asarray(preprocessing["mean"], dtype=np.float32)
    std = np.asarray(preprocessing["std"], dtype=np.float32)
    clip = np.asarray([preprocessing["clip"]], dtype=np.float32)
    if mean.shape != (11,) or std.shape != (11,) or np.any(std <= 0):
        raise ValueError("invalid preprocessing parameters")

    lines = [
        "/* SPDX-License-Identifier: GPL-2.0-only */",
        "/* Generated by generate_fp32_params.py; do not edit manually.",
        f" * model_spec.json sha256: {sha256(args.model_spec)}",
        f" * weights_fp32.npz sha256: {sha256(args.weights)}",
        f" * deployable: {str(bool(spec['deployable'])).lower()}",
        " */",
        "#ifndef SMART_IO_MODEL_FP32_PARAMS_H",
        "#define SMART_IO_MODEL_FP32_PARAMS_H",
        "",
        "static const struct smart_io_model_fp32_scaler_bits smart_io_fp32_scaler = {",
        "\t.mean = {",
        *format_values(mean, "\t\t"),
        "\t},",
        "\t.std = {",
        *format_values(std, "\t\t"),
        "\t},",
        f"\t.clip = 0x{int(clip.view(np.uint32)[0]):08x},",
        "};",
        "",
        "static const struct smart_io_model_fp32_bits smart_io_fp32_model = {",
    ]
    for c_name, _, _ in ARRAYS:
        lines.extend(
            [f"\t.{c_name} = {{", *format_values(weights[c_name], "\t\t"), "\t},"]
        )
    lines.extend(["};", "", "#endif", ""])
    args.output.write_text("\n".join(lines), encoding="ascii", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
